<?php

$GLOBALS['config']['languages']['pt'] = [
    'name' => 'PortuguÃªs',
'messages' => [
        'login' => 'Por favor faÃ§a o login do chat',
'wrongPass' => 'UsuÃ¡rio ou senha incorretos. Por favor tente novamente.',
'anotherlogin' => 'Outro usuÃ¡rio estÃ¡ conectado com esse nome. Por favor tente novamente.',
'expiredlogin' => 'Sua conexÃ£o expirou. Por favor faÃ§a o login novamente.',
'enterroom' => '[ROOM_LABEL]: USER_LABEL entrou em TIMESTAMP',
'leaveroom' => '[ROOM_LABEL]: USER_LABEL saiu em TIMESTAMP',
'selfenterroom' => 'Bem vindo! VocÃª entrou na sala [ROOM_LABEL] em TIMESTAMP',
    ],
'usermenu' => [
        'profile' => 'Perfil',
'unban' => 'Desbanir',
'ban' => 'Banir',
'unignore' => 'Designorar',
'ignore' => 'Ignorar',
'invite' => 'Convidar',
'privatemessage' => 'Mensagem Privada',
    ],
'status' => [
        'away' => 'Ausente',
'busy' => 'Ocupado',
'here' => 'Presente',
    ],
'dialog' => [
        'misc' => [
            'usernotfound' => "UsuÃ¡rio 'USER_LABEL' nÃ£o encontrado",
'unbanned' => "VocÃª foi desbanido pelo usuÃ¡rio 'USER_LABEL':",
'banned' => "VocÃª foi banido pelo usuÃ¡rio 'USER_LABEL':",
'unignored' => "VocÃª foi designorado pelo usuÃ¡rio 'USER_LABEL':",
'ignored' => "VocÃª foi ignorado pelo usuÃ¡rio 'USER_LABEL':",
'invitationdeclined' => "O usuÃ¡rio 'USER_LABEL' recusou seu convite para a sala 'ROOM_LABEL':",
'invitationaccepted' => "O usuÃ¡rio 'USER_LABEL' aceitou seu convite para a sala 'ROOM_LABEL':",
'roomnotcreated' => 'A sala nÃ£o foi criada:',
        ],
'unignore' => [
            'unignoreBtn' => 'Designorar',
'unignoretext' => 'Entre o texto para designorar',
        ],
'unban' => [
            'unbanBtn' => 'Desbanir',
'unbantext' => 'Entre o texto para desbanir',
        ],
'sound' => [
            'sampleBtn' => 'Exemplo',
'testBtn' => 'Teste',
'muteall' => 'Silenciar todos',
'submitmessage' => 'Enviar mensagem',
'reveivemessage' => 'Receber mensagem',
'enterroom' => 'Entrar na sala',
'leaveroom' => 'Sair da sala',
'pan' => 'Pan',
'volume' => 'Volume',
        ],
'skin' => [
            'inputBoxBackground' => 'Fundo de caixa de entrada',
'privateLogBackground' => 'Fundo do log privado',
'publicLogBackground' => 'Fundo do log pÃºblico',
'enterRoomNotify' => 'NotificaÃ§Ã£o de entrada da sala',
'roomText' => 'Texto das salas',
'room' => 'Fundo das salas',
'userListBackground' => 'Fundo da lista de usuÃ¡rios',
'dialogTitle' => 'TÃ­tulo do DiÃ¡logo',
'dialog' => 'Fundo do DiÃ¡logo',
'buttonText' => 'Texto dos botÃµes',
'button' => 'Fundo dos botÃµes',
'bodyText' => 'Texto principal',
'background' => 'Fundo principal',
        ],
'login' => [
            'loginBtn' => 'Login',
'language' => 'Idioma:',
'moderator' => '(se moderador)',
'password' => 'Senha:',
'username' => 'UsuÃ¡rio:',
        ],
'invitenotify' => [
            'declineBtn' => 'Recusar',
'acceptBtn' => 'Aceitar',
'userinvited' => "O usuÃ¡rio 'USER_LABEL' convidou vocÃª para entrar na sala 'ROOM_LABEL':",
        ],
'invite' => [
            'sendBtn' => 'Enviar',
'includemessage' => 'Incluir essa mensagem com seu convite:',
'inviteto' => 'Convidar o usuÃ¡rio para:',
        ],
'ignore' => [
            'ignoreBtn' => 'Ignorar',
'ignoretext' => 'Entrar texto para Ignorar',
        ],
'createroom' => [
            'createBtn' => 'Criar',
'private' => 'Privado',
'public' => 'PÃºblico',
'entername' => 'Entrar nome da sala',
        ],
'ban' => [
            'banBtn' => 'Banir',
'byIP' => 'por IP',
'fromChat' => 'do chat',
'fromRoom' => 'da sala',
'banText' => 'Entrar texto para banir',
        ],
'common' => [
            'cancelBtn' => 'Cancelar',
'okBtn' => 'OK',
        ],
    ],
'desktop' => [
        'invalidsettings' => 'ConfiguraÃ§Ãµes invÃ¡lidas',
'selectsmile' => 'ExpressÃµes',
'sendBtn' => 'Enviar',
'saveBtn' => 'Salvar',
'soundBtn' => 'Som',
'skinBtn' => 'Skin',
'addRoomBtn' => 'Adicionar',
'myStatus' => 'Meu status',
'room' => 'Sala',
'welcome' => 'Bem vindo USER_LABEL',
    ],
];
